project:
  type: website
  output-dir: docs

website:
  title: "Lab 6"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hyperparameter-tuning.qmd
        text: Hyperparameter Tuning

